# Generated by Django 5.2.17 on 2026-09-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qaralama'), ('PUBLISHED', 'Dərc edilib'), ('HIDDEN', 'Gizlədilib')], default='DRAFT', max_length=50),
        ),
        migrations.DeleteModel(
            name='WholesaleTier',
        ),
    ]
