# Generated by Django 5.2.17 on 2026-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_status_delete_wholesaletier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('VISIBLE', 'Görünür'), ('HIDDEN', 'Gizli')], default='VISIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
