# Generated by Django 5.2.17 on 2026-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreport_productreportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
