# Generated by Django 5.2.17 on 2026-09-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='target',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
