# Generated by Django 5.2.17 on 2026-09-22 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stores/covers/')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('theme', models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('boutique', 'Boutique')], default='modern', max_length=50)),
                ('status', models.CharField(choices=[('INVITED', 'Dəvət edilib'), ('CLAIMED', 'Qeydiyyatdan keçib'), ('ACTIVE', 'Aktiv'), ('SUSPENDED', 'Dayandırılıb')], default='INVITED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='stores.store')),
            ],
        ),
    ]
