# Generated by Django 5.2.17 on 2026-09-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_suspension_reason_storereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('boutique', 'Boutique'), ('classic', 'Classic')], default='modern', max_length=50),
        ),
        migrations.CreateModel(
            name='StoreReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.storereport')),
            ],
        ),
    ]
